# -*- coding: utf-8 -*-
"""Copy of Sample_EDA_Submission_Template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUlXrAdpsyctzhubKtJoK_N3Zeoqkl_-
"""



"""# **Project Name**    -   **Amazon Prime TV Shows and Movies**

##### **Project Type**    - Exploratory Data Analysis (EDA)
##### **Contribution**    - Individual
##### **Team Member 1 -**  Ratnadip Dhar

# **Project Summary -**

This project focuses on analyzing a dataset of movies and TV shows to understand patterns, trends, and factors that influence content performance. With the rapid growth of digital streaming platforms, a huge amount of content is being produced every year, making it important to understand what type of content attracts audiences and performs well. The main goal of this project is to explore the dataset and extract meaningful insights that can support better decision-making in content creation and business strategies.

The dataset used in this project consists of two main parts: one containing information about titles such as movies and shows, and the other containing details about the cast and crew, including actors and directors. These datasets were merged using a common identifier to create a unified dataset that provides a complete view of each title along with the people involved in it. This merging step was essential for performing deeper analysis, such as understanding the impact of actors and directors on content success.

Before starting the analysis, several data cleaning and preprocessing steps were performed. Missing values were identified and handled appropriately by filling them with suitable values like mean or median for numerical columns and default values for categorical columns. Duplicate entries were removed to maintain data consistency, and unnecessary columns were dropped to simplify the dataset. Additionally, data types were corrected and text values were cleaned to ensure uniformity. These steps helped in transforming the raw data into a structured and analysis-ready format.

Once the data was prepared, exploratory data analysis (EDA) was carried out using various visualizations. Different types of charts such as histograms, bar charts, line plots, scatter plots, and box plots were used to understand different aspects of the data. The distribution of IMDb scores showed that most content falls within a mid-range rating, indicating that average-rated content is more common. The comparison between movies and TV shows revealed the dominant type of content in the dataset. Trend analysis over the years showed a general increase in content production, highlighting the growth of the entertainment industry.

Further analysis of genres revealed which types of content are most commonly produced and which genres tend to receive higher ratings. It was observed that some genres consistently perform better in terms of audience ratings, while others are more frequently produced. The analysis also explored the role of actors and directors, identifying the most frequent contributors and their involvement in content creation. This helps in understanding how certain individuals may influence the success of movies and shows.

Additional visualizations such as correlation heatmaps and pair plots were used to examine relationships between numerical variables like ratings, runtime, and release year. These analyses showed that while some variables have weak relationships, content quality is not solely dependent on a single factor but rather a combination of multiple aspects. For example, runtime alone does not determine ratings, indicating that storytelling and execution are more important than duration.

Overall, the insights gained from this project highlight the importance of focusing on quality content, understanding audience preferences, and adapting to changing trends. Businesses can use these findings to make informed decisions, such as investing in high-performing genres, collaborating with experienced creators, and maintaining a balance between different types of content. At the same time, it is important to ensure diversity in content to keep audiences engaged and avoid over-reliance on specific patterns.

In conclusion, this project demonstrates how data analysis can be used to uncover valuable insights from large datasets. By applying data cleaning, visualization, and analytical techniques, the project provides a clear understanding of factors that influence content performance. These insights can help businesses improve their strategies, enhance user satisfaction, and achieve sustainable growth in a competitive entertainment industry.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

The objective of this project is to analyze a dataset of movies and TV shows in order to understand patterns related to content type, ratings, genres, and overall performance. With the increasing amount of content available on streaming platforms, it becomes difficult to identify what kind of content attracts more audience and leads to better engagement.

This project aims to explore the data to find meaningful insights that can help in understanding audience preferences, identifying high-performing content, and supporting better decision-making for content creation and business strategies.

#### **Define Your Business Objective?**

To figure out the "winning formula" for movies and TV shows so that streaming platforms and production companies can make smarter investments.

Instead of guessing what audiences want to watch, the goal is to use data to answer:

1. What genres keep people hooked?

2. Which actors and directors consistently deliver hits?

3. What type of content should we produce or acquire next to stay competitive?

Ultimately, it’s about making data-driven decisions to create content that keeps viewers happy, engaged, and coming back for more!

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### Dataset Loading"""

# Load Dataset
# Load Dataset by my actual raw GitHub URLs
url1 = 'https://raw.githubusercontent.com/RatnadipDhar/Amazon-Prime-TV-Shows-and-Movies/refs/heads/main/credits.csv'
url2 = 'https://raw.githubusercontent.com/RatnadipDhar/Amazon-Prime-TV-Shows-and-Movies/refs/heads/main/titles.csv'

df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)

"""###Merge Datasets"""

# Merge datasets on 'id'
df = pd.merge(titles, credits, on='id')

"""### Dataset First View"""

# Dataset First Look
print("Merged Dataset:")
display(df.head())

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print("Titles Dataset Shape:", titles.shape)
print("Credits Dataset Shape:", credits.shape)

# If merged dataset
print("Merged Dataset Shape:", df.shape)

"""### Dataset Information"""

# Dataset Info
print("Titles Dataset Info:")
titles.info()

print("\nCredits Dataset Info:")
credits.info()

print("\nMerged Dataset Info:")
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
print("Titles Duplicate Rows:", titles.duplicated().sum())
print("Credits Duplicate Rows:", credits.duplicated().sum())
print("Merged Dataset Duplicate Rows:", df.duplicated().sum())

"""###Remove Duplicates"""

# Remove duplicate rows
df = df.drop_duplicates()
# Verify again
print("Duplicates after removal:", df.duplicated().sum())

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
print("Titles Dataset Missing Values:\n")
print(titles.isnull().sum())

print("\nCredits Dataset Missing Values:\n")
print(credits.isnull().sum())

print("\nMerged Dataset Missing Values:\n")
print(df.isnull().sum())

# Visualizing the missing values
# Visualizing missing values using heatmap
plt.figure(figsize=(12,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap")
plt.show()

# Missing values count visualization

missing = df.isnull().sum()

missing = missing[missing > 0]  # only columns with missing values

plt.figure(figsize=(10,5))
missing.sort_values(ascending=False).plot(kind='bar')
plt.title("Missing Values Count")
plt.ylabel("Count")
plt.show()

"""### What did you know about your dataset?

I have access to two files that together create a mini-database of movies and TV shows:

Titles (titles.csv): This file holds the main details about different movies and shows. It includes information like the title, whether it's a show or a movie, a short plot description, release year, runtime, genres, and audience ratings (like IMDb and TMDB scores).

Credits (credits.csv): This file focuses on the people involved. It lists the cast and crew for those movies and shows, telling us who acted in or directed them, as well as the names of the characters they played.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
print("Titles Columns:\n", titles.columns)
print("\nCredits Columns:\n", credits.columns)
print("\nMerged Dataset Columns:\n", df.columns)
# Convert to list for better readability
list(df.columns)

# Dataset Describe
df.describe()

"""### Variables Description

The dataset used in this project consists of two main files: titles and credits, which together provide comprehensive information about movies and TV shows.
Titles Dataset
The titles dataset contains general information about each movie or show.
•	id: A unique identifier assigned to each title. It is used to link this dataset with others.
•	title: The name of the movie or TV show.
•	type: Specifies whether the content is a movie or a show.
•	description: A brief summary of the storyline or content.
•	release_year: The year in which the movie or show was released.
•	runtime: The duration of the content, usually in minutes.
•	genres: Categories such as drama, comedy, action, etc., describing the type of content.
•	imdb_score: The rating given by users on IMDb, indicating popularity and quality.
•	imdb_votes: The total number of votes received on IMDb.
•	tmdb_score: The rating provided by TMDb (The Movie Database).
 Credits Dataset
The credits dataset provides information about the people involved in each title.
•	person_id: A unique identifier for each individual (actor, director, etc.).
•	id: The title ID used to connect with the titles dataset.
•	name: The name of the actor or director.
•	character: The role or character played by the actor in the movie/show.
•	role: Defines whether the person is an actor or a director.
Merged Dataset
By merging both datasets using the common id column, we obtain a unified dataset that combines content details with cast and crew information. This allows for deeper analysis, such as understanding the relationship between actors, genres, and ratings.
Overall, these variables help in analyzing trends, popularity, and patterns in movies and TV shows, which can further be used for tasks like recommendation systems and data visualization.

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
df.nunique()

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
# 1. Remove duplicate rows
df = df.drop_duplicates()

# 2. Handle missing values
# Drop columns with too many missing values
df = df.dropna(axis=1, thresh=len(df)*0.5)# keep columns with at least 50% data
# Fill missing values for important columns
df['imdb_score'] = df['imdb_score'].fillna(df['imdb_score'].mean())
df['tmdb_score'] = df['tmdb_score'].fillna(df['tmdb_score'].mean())
df['runtime'] = df['runtime'].fillna(df['runtime'].median())
df['genres'] = df['genres'].fillna('Unknown')

# 3. Convert data types
df['release_year'] = df['release_year'].astype(int)

# 4. Remove unnecessary columns
df = df.drop(columns=['description'], errors='ignore')

# 5. Strip extra spaces for string columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

# 6. Check final dataset
print("Final Dataset Shape:", df.shape)
df.head()

"""### What all manipulations have you done and insights you found?

The dataset was cleaned and organized so that it could be used effectively for analysis. Missing values were handled carefully by filling them with suitable values, and duplicate entries were removed to avoid incorrect results. Unnecessary columns were dropped to keep the dataset simple and relevant. Both datasets were then combined using a common column, which helped in bringing together all the important information in one place. Small corrections like fixing data types and cleaning text values were also done to make the data more consistent.
After these changes, the dataset became much more structured and easier to work with. It was noticed that some information, especially ratings and runtime, was missing in places, and there were repeated entries that needed cleaning. The combined dataset now provides a clearer view of movies and shows along with their related details, making it suitable for further analysis and building models.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code
# Chart - 1: Distribution of IMDb Scores

plt.figure(figsize=(10,5))
sns.histplot(df['imdb_score'], bins=20, kde=True)

plt.title("Distribution of IMDb Scores")
plt.xlabel("IMDb Score")
plt.ylabel("Count")

plt.show()

"""##### 1. Why did you pick the specific chart?

The histogram was chosen because it clearly shows how the IMDb scores are distributed across different ranges, making it easy to understand the overall pattern of ratings.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that most movies and shows fall in the mid-range of ratings, indicating that average-rated content is more common than extremely high or low-rated content.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights can help improve content quality by focusing on producing higher-rated content to attract more users. However, the lack of highly rated content may indicate weaker audience engagement, which could negatively affect growth if not addressed.Answer Here

#### Chart - 2
"""

# Chart - 2 visualization code
# Chart - 2: Count of Movies vs Shows

plt.figure(figsize=(6,4))
sns.countplot(x='type', data=df)

plt.title("Movies vs Shows Distribution")
plt.xlabel("Type")
plt.ylabel("Count")

plt.show()

"""##### 1. Why did you pick the specific chart?

This chart was chosen because it provides a clear and simple comparison between movies and shows, making it easy to understand the distribution of content types in the dataset.

##### 2. What is/are the insight(s) found from the chart?

The chart shows which type of content is more dominant, either movies or shows, helping to identify the overall focus of the dataset.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, this insight helps businesses understand content demand and decide where to invest more. However, if one type dominates too much, it may indicate a lack of variety, which could reduce user interest over time.

#### Chart - 3
"""

# Chart - 3 visualization code
# Chart - 3: Number of titles released each year

plt.figure(figsize=(12,6))

df['release_year'].value_counts().sort_index().plot(kind='line')

plt.title("Number of Titles Released Over the Years")
plt.xlabel("Release Year")
plt.ylabel("Count")

plt.show()

"""##### 1. Why did you pick the specific chart?

This line chart was chosen because it clearly shows the trend of content release over time, making it easy to understand growth patterns across years.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that the number of movies and shows has generally increased over the years, indicating growth in content production, especially in recent times.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, this insight helps businesses understand market growth and plan future content production. However, a rapid increase in content may lead to high competition and difficulty in maintaining quality, which could negatively impact user satisfaction.

#### Chart - 4
"""

# Chart - 4 visualization code
# Chart - 4: Top 10 Genres

# Split genres (if multiple genres in one row)
genres_series = df['genres'].dropna().str.split(',').explode()

plt.figure(figsize=(10,5))
genres_series.value_counts().head(10).plot(kind='bar')

plt.title("Top 10 Genres")
plt.xlabel("Genres")
plt.ylabel("Count")

plt.show()

"""##### 1. Why did you pick the specific chart?

This bar chart was chosen because it clearly compares different genres and makes it easy to identify the most common ones in the dataset.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that certain genres appear more frequently than others, indicating which types of content are more commonly produced.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses focus on popular genres to attract more viewers. However, over-reliance on a few genres may reduce content variety, which could lead to lower audience interest over time.

#### Chart - 5
"""

# Chart - 5 visualization code
# Chart - 5: Top 10 Highest Rated Titles

top_rated = df.sort_values(by='imdb_score', ascending=False).head(10)

plt.figure(figsize=(10,5))
sns.barplot(x='imdb_score', y='title', data=top_rated)

plt.title("Top 10 Highest Rated Titles (IMDb)")
plt.xlabel("IMDb Score")
plt.ylabel("Title")

plt.show()

"""##### 1. Why did you pick the specific chart?

This bar chart was chosen because it clearly highlights and compares the highest-rated titles, making it easy to identify top-performing content.

##### 2. What is/are the insight(s) found from the chart?

The chart shows which movies or shows have the highest IMDb scores, indicating the most well-received and high-quality content in the dataset.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses understand what kind of content performs best and guide future production decisions. However, focusing only on top-rated content may ignore diverse audience preferences, which could limit overall engagement.

#### Chart - 6
"""

# Chart - 6 visualization code
# Chart - 6: IMDb Score comparison by type

plt.figure(figsize=(8,5))
sns.boxplot(x='type', y='imdb_score', data=df)

plt.title("IMDb Score Comparison: Movies vs Shows")
plt.xlabel("Type")
plt.ylabel("IMDb Score")

plt.show()

"""##### 1. Why did you pick the specific chart?

This box plot was chosen because it effectively compares the distribution of IMDb scores between movies and shows, while also showing variations and outliers.

##### 2. What is/are the insight(s) found from the chart?

The chart shows how ratings differ between movies and shows, helping to identify which type generally performs better and how consistent the ratings are.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, this insight helps businesses focus on the type of content that receives better ratings and improve their strategy. However, if one type consistently underperforms, it may indicate lower audience interest, which could negatively impact growth if not improved.

#### Chart - 7
"""

# Chart - 7 visualization code
# Chart - 7: Runtime vs IMDb Score

plt.figure(figsize=(10,5))
sns.scatterplot(x='runtime', y='imdb_score', data=df)

plt.title("Runtime vs IMDb Score")
plt.xlabel("Runtime (minutes)")
plt.ylabel("IMDb Score")

plt.show()

"""##### 1. Why did you pick the specific chart?

This scatter plot was chosen because it helps in understanding the relationship between runtime and IMDb score, showing how one variable may affect the other.

##### 2. What is/are the insight(s) found from the chart?

The chart suggests that there is no strong relationship between runtime and ratings, as both short and long content can have high or low scores.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, this insight helps businesses understand that content quality matters more than duration. However, investing heavily in longer content without improving quality may not lead to better results and could negatively impact resources and returns.

#### Chart - 8
"""

# Chart - 8 visualization code
# Chart - 8: IMDb Score by Genre (Top 5 genres)

# Split genres and keep main genre
df_genre = df.copy()
df_genre['genres'] = df_genre['genres'].str.split(',').str[0]

# Get top 5 genres
top_genres = df_genre['genres'].value_counts().head(5).index

filtered_df = df_genre[df_genre['genres'].isin(top_genres)]

plt.figure(figsize=(10,5))
sns.boxplot(x='genres', y='imdb_score', data=filtered_df)

plt.title("IMDb Score Distribution by Top Genres")
plt.xlabel("Genre")
plt.ylabel("IMDb Score")

plt.show()

"""##### 1. Why did you pick the specific chart?

This box plot was chosen because it allows easy comparison of IMDb scores across different genres and shows the variation in ratings within each genre.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that some genres tend to have higher ratings than others, and there is variation within each genre, indicating differences in content quality.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses focus on genres that perform well and attract more audience. However, focusing too much on a few high-performing genres may reduce diversity in content, which could limit audience reach and lead to negative growth.

#### Chart - 9
"""

# Chart - 9 visualization code
# Chart - 9: Top 10 Most Frequent Actors

# Filter only actors
actors_df = df[df['role'] == 'ACTOR']

top_actors = actors_df['name'].value_counts().head(10)

plt.figure(figsize=(10,5))
top_actors.plot(kind='bar')

plt.title("Top 10 Most Frequent Actors")
plt.xlabel("Actor Name")
plt.ylabel("Number of Appearances")

plt.show()

"""##### 1. Why did you pick the specific chart?

This bar chart was chosen because it clearly shows and compares the actors with the highest number of appearances, making it easy to identify the most frequent contributors.

##### 2. What is/are the insight(s) found from the chart?

The chart shows which actors appear most often in the dataset, indicating their high level of involvement and popularity in content production.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, this insight helps businesses identify popular actors who can attract more audience and improve engagement. However, relying too much on a few actors may reduce diversity and increase risk if audience preferences change.

#### Chart - 10
"""

# Chart - 10 visualization code
# Chart - 10: IMDb Score vs Release Year

plt.figure(figsize=(10,5))
sns.scatterplot(x='release_year', y='imdb_score', data=df)

plt.title("IMDb Score vs Release Year")
plt.xlabel("Release Year")
plt.ylabel("IMDb Score")

plt.show()

"""##### 1. Why did you pick the specific chart?

This scatter plot with a trend line was chosen because it helps visualize how IMDb scores change over time and makes it easy to observe any overall trend in content quality.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that IMDb scores remain fairly consistent over the years, with no major increase or decrease, indicating that content quality has been relatively stable.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, this insight helps businesses understand that maintaining consistent quality is important for long-term success. However, the lack of improvement over time may suggest missed opportunities to enhance content quality, which could limit growth in a competitive market.

#### Chart - 11
"""

# Chart - 11 visualization code
# Chart - 11: Average IMDb Score by Genre

# Take first genre
df_genre = df.copy()
df_genre['genres'] = df_genre['genres'].str.split(',').str[0]

# Calculate average score per genre
genre_avg = df_genre.groupby('genres')['imdb_score'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
genre_avg.plot(kind='bar')

plt.title("Top Genres by Average IMDb Score")
plt.xlabel("Genre")
plt.ylabel("Average IMDb Score")

plt.show()

"""##### 1. Why did you pick the specific chart?

This bar chart was chosen because it clearly compares the average IMDb scores across different genres, making it easy to identify which genres perform better overall.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that some genres consistently receive higher average ratings than others, indicating better audience reception and content quality in those genres.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses focus on high-performing genres to improve audience engagement. However, focusing only on top-rated genres may reduce content diversity, which could limit audience reach and lead to negative growth.

#### Chart - 12
"""

# Chart - 12 visualization code
# Chart - 12: Genre trend over time

# Take first genre (if multiple)
df_genre = df.copy()
df_genre['genres'] = df_genre['genres'].str.split(',').str[0]

# Get top 5 genres
top_genres = df_genre['genres'].value_counts().head(5).index

filtered_df = df_genre[df_genre['genres'].isin(top_genres)]

# Pivot table
genre_trend = filtered_df.groupby(['release_year', 'genres']).size().unstack().fillna(0)

# Plot
genre_trend.plot(figsize=(12,6))

plt.title("Genre Trend Over Time")
plt.xlabel("Release Year")
plt.ylabel("Number of Titles")

plt.show()

"""##### 1. Why did you pick the specific chart?

This line chart was chosen because it clearly shows how different genres have changed over time, making it easy to understand trends in content production.

##### 2. What is/are the insight(s) found from the chart?

The chart shows that some genres have grown in popularity over the years while others have remained stable or declined, indicating shifting audience preferences.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses focus on trending genres to attract more viewers and stay competitive. However, ignoring less popular genres completely may reduce variety, which could limit audience reach and lead to negative growth.

#### Chart - 13
"""

# Chart - 13 visualization code
# Chart - 13: Top 10 Directors

# Filter only directors
directors_df = df[df['role'] == 'DIRECTOR']

top_directors = directors_df['name'].value_counts().head(10)

plt.figure(figsize=(10,5))
top_directors.plot(kind='bar')

plt.title("Top 10 Directors by Number of Titles")
plt.xlabel("Director Name")
plt.ylabel("Number of Titles")

plt.show()

"""##### 1. Why did you pick the specific chart?

This bar chart was chosen because it clearly shows and compares the directors with the highest number of titles, making it easy to identify the most active contributors.

##### 2. What is/are the insight(s) found from the chart?

The chart shows which directors have created the most content, indicating their strong involvement and influence in content production.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses collaborate with experienced and active directors to produce more content. However, relying too much on a few directors may limit creativity and diversity, which could affect audience interest over time.

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

# Select only numeric columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

plt.figure(figsize=(10,6))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

"""##### 1. Why did you pick the specific chart?

The correlation heatmap was chosen because it clearly shows the relationship between numerical variables in a single view, making it easy to identify patterns and dependencies.

##### 2. What is/are the insight(s) found from the chart?

The chart shows how variables like ratings, votes, and runtime are related to each other, helping to identify which features have strong or weak relationships.

3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses focus on factors that influence ratings and performance. However, relying only on correlated variables without considering other factors may lead to incomplete decisions and affect overall outcomes.

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code

# Select important numeric columns
selected_cols = ['imdb_score', 'tmdb_score', 'runtime', 'release_year']

sns.pairplot(df[selected_cols])

plt.show()

"""1. Why did you pick the specific chart?

The pair plot was chosen because it allows multiple variables to be compared at once, making it easy to observe relationships and patterns between them.

2. What is/are the insight(s) found from the chart?

The chart shows how different numerical variables are related, highlighting possible correlations and patterns between ratings, runtime, and release year.

3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, these insights help businesses understand key factors that influence performance and make better decisions. However, misinterpreting relationships or assuming correlation as causation may lead to incorrect strategies and negative outcomes.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

To achieve the business objective, it is important for the client to focus on creating high-quality content that aligns with audience preferences. Based on the analysis, genres and content types that consistently receive higher ratings should be prioritized, as they are more likely to attract and retain viewers. At the same time, maintaining a balance between movies and shows can help cater to a wider audience.

The client should also collaborate with popular actors and experienced directors, as they tend to contribute to successful content. Monitoring trends over time is equally important, as it helps in identifying which types of content are gaining popularity and allows the business to adapt accordingly.

Additionally, instead of focusing only on quantity, the client should emphasize improving content quality, since higher-rated content has a greater impact on audience engagement and satisfaction. By combining data-driven decisions with creative strategies, the client can enhance user experience, increase viewership, and achieve long-term growth.

# **Conclusion**

In this project, the dataset was cleaned, analyzed, and visualized to understand patterns in movies and shows. The analysis highlighted important factors such as ratings, genres, trends over time, and the role of actors and directors in content performance. It was observed that content quality, popular genres, and audience preferences play a key role in determining success.

Overall, the insights gained from the data can help in making better decisions for content creation and strategy. By focusing on quality and understanding trends, businesses can improve user engagement and achieve steady growth.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""



